fix `get_lib_name` (#280)
* fix `get_lib_name`

before it fails with `TypeError: _metadata() missing 1 required positional argument: 'cargo'`

* Add changelog and test

Co-authored-by: David Hewitt <1939362+davidhewitt@users.noreply.github.com>